[package]
name = "lapin-issue-133-example"
version = "0.1.0"
authors = ["tyranron <tyranron@gmail.com>"]
publish = false

[dependencies]
amq-protocol = "0.21"
futures = "0.1"
lapin-async = "0.13"
lapin-futures = "0.13"
log = "0.4"
stderrlog = "0.4"
tokio = "0.1"
